[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "prague"
ffi = false

[rpc_endpoints]
# Official public testnet RPC from https://docs.monad.xyz/developer-essentials/testnet
monad_testnet = "https://testnet-rpc.monad.xyz"
local = "http://127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
